export const meta = {
  name: 'doc-translate',
  description: 'Translate+classify prepped document pages (vision fan-out, batched per agent) then reconcile a canonical glossary',
  phases: [
    { title: 'Translate', detail: 'each agent translates a batch of pages: reads overlay+page.json per page, writes one llm patch per page, returns a glossary fragment' },
    { title: 'Reconcile', detail: 'one agent merges all glossary fragments into a canonical source→target map + conflict list' },
  ],
}

// args (passed by the run skill, derived from projects/<name>/config.json):
//   root           artifacts dir holding overlay/, json/, llm/   (required)
//   pages          array of page tokens matching p-<token>.png    (required, or range)
//   range          {first,last,pad} to generate pages instead     (optional)
//   source_lang    e.g. "sv"                                      (required)
//   target_lang    e.g. "en"                                      (required)
//   domain_context one-paragraph translation guidance             (required)
//   glossary_path  path to a glossary json to reuse/extend        (optional)
//   batch          pages handled per agent (default 1 = per-page) (optional)
//   model          'sonnet'|'haiku'|'opus' or undefined to inherit (optional)
let A = args || {}
if (typeof A === 'string') { try { A = JSON.parse(A) } catch (e) { /* leave as-is */ } }
const ROOT = A.root
let PAGES = A.pages || []
if (!PAGES.length && A.range) {
  const pad = A.range.pad || 4
  for (let i = A.range.first; i <= A.range.last; i++) PAGES.push(String(i).padStart(pad, '0'))
}
const SRC = A.source_lang || 'sv'
const TGT = A.target_lang || 'en'
const CTX = A.domain_context || ''
const GLOSS = A.glossary_path || `${ROOT}/glossary.json`
// source blocks: default the slim translate-view (uid/order/class/src text only),
// generated by translate_view.py — geometry stays out of the prompt.
const SRCDIR = A.src_subdir || 'trans'
const SRCSUFFIX = A.src_suffix || '.page.json'
const BATCH = Math.max(1, A.batch || 1)
const MODEL = A.model // undefined => inherit main-loop model; 'sonnet'|'haiku'|'opus' to pin
if (!ROOT || !PAGES.length) throw new Error('doc-translate: args.root and args.pages (or args.range) are required')

// chunk pages into per-agent batches
const BATCHES = []
for (let i = 0; i < PAGES.length; i += BATCH) BATCHES.push(PAGES.slice(i, i + BATCH))

const TRANSLATE_SCHEMA = {
  type: 'object',
  required: ['pages', 'glossary'],
  properties: {
    pages: {
      type: 'array',
      items: {
        type: 'object',
        required: ['page', 'n_blocks'],
        properties: {
          page: { type: 'string' },
          n_blocks: { type: 'integer' },
          n_recovered: { type: 'integer' },
        },
      },
    },
    glossary: { type: 'object', additionalProperties: { type: 'string' } },
    notes: { type: 'string' },
  },
}

const RECON_SCHEMA = {
  type: 'object',
  required: ['canonical', 'conflicts'],
  properties: {
    canonical: { type: 'object', additionalProperties: { type: 'string' } },
    conflicts: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          src: { type: 'string' },
          options: { type: 'array', items: { type: 'string' } },
          chosen: { type: 'string' },
        },
      },
    },
  },
}

const fileList = (pages) =>
  pages
    .map(
      (n) =>
        `  p-${n}:  overlay=${ROOT}/overlay/p-${n}.grid.png  source=${ROOT}/${SRCDIR}/p-${n}${SRCSUFFIX}  ->write=${ROOT}/llm/p-${n}.llm.json`
    )
    .join('\n')

const batchPrompt = (pages) => `You are the translate+classify stage of the Palimpsest document pipeline. Translate ${SRC} → ${TGT}.

## Document context
${CTX}

## Your batch: ${pages.length} page(s)
Process these pages ONE AT A TIME, fully finishing one page's output file before starting the next. Do NOT mix blocks or uids between pages.
${fileList(pages)}

## Shared glossary (read ONCE, reuse for EVERY page in this batch)
Running glossary at ${GLOSS} — REUSE these term choices for consistency across all your pages. Read it once at the start; you do not need to re-read it per page.

Each source JSON is a SLIM translate-view: {blocks:[{uid, order, class (a guess), ${SRC} (source text)}]}. It carries no geometry — you only classify + translate; positions are merged back by uid downstream.

## For each page: read its gridded overlay image + its slim source JSON, then for EVERY block decide
- class ∈ {prose, heading, step, warning, caption, label, part_number, identifier, header_band, table, other}
  - step = numbered procedure line (keep the leading number); caption = figure caption; warning = warning/note callout; header_band = page header line → translate=false; part_number/identifier = tool/part/drawing numbers → translate=false, byte-identical.
  - table = a cell in a data table. TRANSLATE descriptive cells; keep numeric/part-number cells verbatim. Never leave a table cell's ${TGT} empty.
- translate: false for header_band/part_number/identifier; true otherwise.
- ${TGT}: the translation. For translate=false, COPY the source verbatim into the ${TGT} field (never leave it empty). Preserve ALL digits exactly.

The overlay has a faint coord grid (columns numbered along the top, rows down the left) and numbered+colored boxes labeled with each block's \`order\`. Use grid coordinates ONLY to locate text the OCR missed.

## Text is already detected — do NOT re-recover it
In-figure labels are PRE-DETECTED and already present as source blocks (boxed on the overlay) — translate+classify them like any other block. Do NOT add them again as \`recovered\`. Only use \`recovered\` for text plainly visible on the page yet with NO box at all (e.g. a missed header band): {grid_ref:{c0,r0,c1,r1}, class, ${SRC}, ${TGT}}. Prefer an empty recovered list.

## Write one result file PER PAGE (this is the real output)
For each page p-<n>, write ONLY this JSON to ${ROOT}/llm/p-<n>.llm.json :
{ "blocks":[{"uid","class","translate","${TGT}"},...], "recovered":[{"grid_ref":{c0,r0,c1,r1},"class","${SRC}","${TGT}"},...], "glossary":{"srcterm":"tgtterm",...} }
Include a blocks entry for EVERY uid in that page's source.

## Return (structured)
Return: pages=[{page:"<n>", n_blocks, n_recovered}, ...] for every page you processed, glossary (the merged source→target map you used across the batch), and a one-line notes string.`

phase('Translate')
log(`translating ${PAGES.length} page(s) in ${BATCHES.length} batch(es) of up to ${BATCH}`)
const results = await parallel(
  BATCHES.map((pages, bi) => () =>
    agent(batchPrompt(pages), {
      label: `translate:b${bi}:p-${pages[0]}..${pages[pages.length - 1]}`,
      phase: 'Translate',
      schema: TRANSLATE_SCHEMA,
      agentType: 'general-purpose',
      model: MODEL,
    })
  )
)

const ok = results.filter(Boolean)
// normalize page tokens (agents sometimes echo "p-0161" instead of the bare "0161")
const norm = (t) => String(t).replace(/^p-/, '')
const donePages = ok.flatMap((r) => (r.pages || []).map((p) => norm(p.page)))
const fragments = ok.map((r, i) => ({ batch: i, pages: (r.pages || []).map((p) => norm(p.page)), glossary: r.glossary }))
log(`translated ${donePages.length}/${PAGES.length} pages across ${ok.length}/${BATCHES.length} batches`)

// Reconcile only when there's cross-batch terminology to merge.
let canonical = { canonical: {}, conflicts: [] }
if (fragments.length > 1) {
  phase('Reconcile')
  canonical = await agent(
    `You are reconciling terminology across a ${SRC}→${TGT} technical translation.
Document context: ${CTX}

Per-batch glossary fragments (${SRC}→${TGT}) from ${fragments.length} batches:
${JSON.stringify(fragments, null, 2)}

Produce ONE canonical ${SRC}→${TGT} glossary: for each source term pick the single best target term, normalizing inconsistencies. Where batches disagreed, record a conflict {src, options:[...], chosen}.
Return {canonical:{src:tgt,...}, conflicts:[...]}.`,
    { label: 'reconcile-glossary', phase: 'Reconcile', schema: RECON_SCHEMA, agentType: 'general-purpose', model: MODEL }
  )
} else if (fragments.length === 1) {
  canonical = { canonical: fragments[0].glossary || {}, conflicts: [] }
}

return {
  pages_done: donePages,
  pages_failed: PAGES.filter((n) => !donePages.includes(n)),
  batches: BATCHES.length,
  glossary_terms: Object.keys(canonical?.canonical || {}).length,
  conflicts: canonical?.conflicts || [],
  canonical: canonical?.canonical || {},
}
